ShoppingCart/Controllers/LoginController.cs
using Business;
using Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using DataBases;
using Org.BouncyCastle.Crypto.Generators;

namespace ShoppingCart.Controllers
{
    public class LoginController : Controller
    {
        accountBusiness _accBusiness;
        public LoginController(IDB _db)
        {
            _accBusiness = new accountBusiness(_db);
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> LoggedIn(account account)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var errors = ModelState.Values.SelectMany(v => v.Errors)
                        .Select(e => e.ErrorMessage).ToList();
                    return BadRequest(Json(errors));
                    // return BadRequest(Json(errors.FirstOrDefault())); // 返回第一个错误
                }

                var user = await _accBusiness.Get(account.id);
                if (user == null)
                {
                    throw new Exception("帳號不存在");
                }
                if (!_accBusiness.Verify(account.pwd, user.pwd))
                {
                    throw new Exception("密碼錯誤");
                }
                await HttpContext.SignIn(user);

                return Ok();
            }
            catch (Exception ex)
            {
                Log.Error(ex.Message);
                return BadRequest(Json(ex.Message));
            }
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> SaveAccount(account account)
        {
            try
            {
                await _accBusiness.Insert(account);
                return Ok();

            }
            catch (Exception ex)
            {
                Log.Error(ex.Message);
                return BadRequest(Json(ex.Message));
            }
        }
    }
}

ShoppingCart/Controllers/MyProductController.cs
using Business;
using Models;
using Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Serilog;
using DataBases;

namespace ShoppingCart.Controllers
{
    [Authorize]
    public class MyProductController : Controller
    {
        commodityBusiness _commodityBusiness;
        public MyProductController(IDB _db) 
        {
            _commodityBusiness = new commodityBusiness(_db);
        }
        public async Task<IActionResult> Index()
        {
            var userName = HttpContext.User.Identity.Name;
            if (string.IsNullOrEmpty(userName)) return RedirectToAction("Index", "Home");
            account? acc = JsonConvert.DeserializeObject<account>(userName);
            if (acc == null) return RedirectToAction("Index", "Home");
            List<commodity> MyProducts =await _commodityBusiness.GetList(acc.pk);
            ViewBag.MyProducts = MyProducts.Select(x => new
            {
                pic=Url.Content("~/files/pic/")+ x.pic,
                x.pk,
                x.name,
                x.price,
            }).Json();
            return View();
        }
        [HttpPost]
        public async Task<int> Set(string commodityJson, int AccPk, IFormFile file)
        //public async Task<int> Set([FromForm] company _company, [FromForm] int AccPk, [FromForm] IFormFile file)
        {
            return await _commodityBusiness.Set(commodityJson, AccPk, file);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int pk)
        {
            try
            {
                await _commodityBusiness.Delete(pk);
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(Json(ex.Message));
            }
        }
    }
}

ShoppingCart/Controllers/ShoppingCartController.cs
using Business;
using Models;
using Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Serilog;
using Models.ViewModels;
using DataBases;
using System.Collections.Generic;

namespace ShoppingCart.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        orderBusiness _orderBusiness;
        public ShoppingCartController(IDB _db)
        {
            _orderBusiness = new orderBusiness(_db);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var cartCookie = HttpContext.Request.Cookies["cart"];

            if (cartCookie == null)
            {
                ViewBag.MyProducts = new List<shoppingCartViewModel>();
                return View();
            }

            List<shoppingCartViewModel> MyProducts = await _orderBusiness.GetList(cartCookie, Url.Content("~/files/pic/"));
            ViewBag.MyProducts = MyProducts.Select(x => new
            {
                x.pk,
                x.name,
                x.price,
                x.count,
                pic = Url.Content("~/files/pic/") + x.pic,
            }).Json();

            // var userName = HttpContext.User.Identity.Name;
            // if (string.IsNullOrEmpty(userName)) return RedirectToAction("Index", "Home");
            // account? acc = JsonConvert.DeserializeObject<account>(userName);
            // if (acc == null) return RedirectToAction("Index", "Home");
            // List<shoppingCartViewModel> MyProducts = await _orderBusiness.GetList(4);

            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Delete(int pk)
        {
            try
            {
                var cartCookie = HttpContext.Request.Cookies["cart"];

                if (!string.IsNullOrEmpty(cartCookie))
                {
                    // 解析 Cookie 中的购物车数据
                    List<CartItem>? cartItems = JsonConvert.DeserializeObject<List<CartItem>>(cartCookie);
                    // 移除特定 commodityPk 的项
                    cartItems.RemoveAll(item => item.commodityPk == pk);
                    // 将更新后的购物车数据转换为 JSON 字符串
                    string updatedCartJson = JsonConvert.SerializeObject(cartItems);
                    // 更新 Cookie
                    HttpContext.Response.Cookies.Append("cart", updatedCartJson, new CookieOptions {Expires = DateTime.Now.AddDays(7) });
                }

                //await _orderBusiness.Delete(pk);
                return Ok();
            }
            catch (Exception ex)
            {
                return BadRequest(Json(ex.Message));
            }
        }
    }
}

ShoppingCart/Views/Shared/_Layout.cshtml
@{
    var user = Context.User() ?? new();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingCart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ShoppingCart.styles.css" asp-append-version="true" />
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="~/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css" />
    @await RenderSectionAsync("head", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShoppingCart</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">首頁</a>
                        </li>
                        @if (string.IsNullOrEmpty(user.id))
                        {
                            <li class="nav-item" style="float:right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">購物車</a>
                            </li>
                            <li class="nav-item" style="float:right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">登入</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item" style="float:right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MyProduct" asp-action="Index">我的商品</a>
                            </li>
                            <li class="nav-item" style="float:right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MyOrder" asp-action="Index">我的訂單</a>
                            </li>
                            <li class="nav-item" style="float:right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">購物車</a>
                            </li>
                            <li class="nav-item" style="float:right">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">登出</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ShoppingCart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @* <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- SweetAlert2 -->
    <script src="~/sweetalert2/sweetalert2.all.min.js"></script>
    <!-- js-cookie -->
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <!-- Vue.js -->
    <script src="~/js/vue.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>